#日志路径配置
logging:
  config:
    classpath:logback-spring.xml
  file:
    path: .

idgenerator:
  datacenterId: 1
  machineId: 2

#spring配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kx_game?&allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ETMcagEdKb6lVXMN7XyexuPJUAVbtG8bPQb9VVbYEW85zi2VO2XJPfs8u5j5Ww/FfW62uvE1tbhcSjL65HgPjQ==
    public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAOFeQmOccCPqvHMoj7dNG6++938v7NjqNbolx+H+WCuU/PIzEz3vjHGT1MAhIG2zgt9Rk25LnXaXyY2cyH4/jokCAwEAAQ==
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.public-key}
      initial-size: 2
      max-active: 32
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      min-idle: 1
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 30001
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 1000
  redis:
    # Redis数据库索引（默认为0）
    database: 3
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  thymeleaf:
    prefix: classpath:/static/
    cache: false
  profiles:
    active: default
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    time-zone: Asia/Shanghai

mybatis-plus:
  # 支持统配符 * 或者 ; 分割
  type-handlers-package: com.iv.ersr.*.typehandler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#服务端口配置
server:
  port: 7992
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    context-path: /openapi
  tomcat:
    background-processor-delay: 30
    uri-encoding: UTF-8
  #传输压缩配置
  compression:
    enabled: false
    mime-types: text/html,text/xml,text/javascript,text/css,text/plain,application/json,application/javascript,image/svg+xml
    min-response-size: 2KB
